### ISSUE TITLE
de-aggregation interoperability with official KPL

### ISSUE THREAD

**Issue by ihorkhavkin** [harlow/kinesis-connectors#22]
De-aggregation of KPL UserRecord ( https://github.com/awslabs/amazon-kinesis-producer/blob/master/aggregation-format.md ) is not supported, right?

**Comment by harlow** [comment]
Hi @ihorkhavkin thanks for the link. I haven't see that before. Is there a reason to use that over the `PutRecords` batch that Kinesis supports via API? 

http://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html

**Comment by ihorkhavkin** [comment]
I believe AWS still charges you based on 25KB PUT payload units and also there are limits on TPS ( http://docs.aws.amazon.com/kinesis/latest/dev/service-sizes-and-limits.html 1K TPS for PUT regardless of `PutRecords` batching)

So aggregation on KPL side helps when you have smaller records. And with some latency impact it can make Kinesis bound only by bandwidth (1 Mb/s per shard on write). So if you are not using aggregation, you may end up paying much more due to higher number of shards and number of PUTs.

**Comment by ihorkhavkin** [comment]
http://brianoneill.blogspot.com/2015/09/kinesis-20x-cheaper-when-used-with.html more detailed write up about aggregation impact on Kinesis pricing when you have records significantly smaller than 25Kb

**Comment by harlow** [comment]
Thanks for the note about reduced pricing. For the time being I'd like to keep things simple and use string to string on and off the wire.
