### ISSUE TITLE
How do I change redis endpoint?

### ISSUE THREAD

**Issue by jsam** [harlow/kinesis-connectors#28]
Hello,

Thank you for great library. I'm successfully using your library in production for some time now, however we have new systems requirements where I can't have Redis running on localhost. How do I easily update Redis address without editing your library? 

Thanks

**Comment by harlow** [comment]
I think the redis library will look at REDIS_URL from ENV vars if it
exists.

**Comment by harlow** [comment]
If that's not the case I'll add it as a config option

**Comment by jsam** [comment]
Yes, I did try that before writing the post and I have also read the redis library code. Sadly, that lib is not reading anything from the env as far as I see. Their default address is private and I cannot change it directly, so if you could add a proxy option to the Checkpointer/Config type that would be awesome.

I need this kinda quick, so if you could write me what solution you would accept I could help you out and send you a PR.

Thanks for quick reply.

**Comment by harlow** [comment]
Gotcha. Thanks for looking into the ENV var. I

should be able to whip something up this eve. If you need something
immediately I'd suggest forking the repo and then just patching your
version until we get a fix pushed .
